### ISSUE TITLE
Code Review for Assignment

### ISSUE THREAD

**Issue by narinmahmuti** [bounswe/bounswe2015group7#163]
Hey @atakanarikan , could you review the following commit and give me some feedback by the end of the day? Thanks in advance!
https://github.com/bounswe/bounswe2015group7/commit/ad2be5369ba66162ff25ab1a71f6fe72beb58c64

**Comment by atakanarikan** [comment]
Allright! Will do the review as soon as possible.

**Comment by atakanarikan** [comment]
Hey Narin, sorry for late response, I was working with another project.

As far as I can see you added 2 html pages. When I tried they were looking and functioning fine. However, I have a couple of points:
- I saw there are some redundant lines, especially in scripts. This could be my bad as well since I did not comment my code properly, note taken.
- Please try to add more comments, they are super helpful for an outsider. But don't just add comments for the sake of adding. Having bad commented code is even worse than having no commented one.
- Your intendation is quite good. However, I'm kind of obsessed with indentation, especially in the script tag (lines 300-310) please don't forget to add "\t" in the beginning of a line.
- Your commit message was fine, qutie self-explanotory, thanks for that!

I guess that's all, let me know if you need more feedback, I'd be glad to help.
Best,
A.
