### ISSUE TITLE
Code review for commit 875fbf7

### ISSUE THREAD

**Issue by atakanarikan** [bounswe/bounswe2015group7#164]
Yo @narinmahmuti , can you please review the code I submitted in the commit 46bd89f23e80448a054d67beb10b52ed81b575fc ? Looking forward to your feedback.

Cheers,
A.

**Comment by narinmahmuti** [comment]
Will do asap!

**Comment by narinmahmuti** [comment]
Hey Ata, reviewed your code just now. I think you did a great job overall. No bugs that I could find, but a few things caught my eye:
- Maybe pay attention to indentation a little bit more in the future, it will be really helpful in terms of readability and overall will look much better
- Also try and add more comments so that in times like these when other people read your code they'll have a better idea of what's going on :)
-  I'd work a little on writing better commit messages, here's a great source you can check out: https://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message
- You could provide some unit tests for the code (not sure what would work with JSP though since I don't think JUnit works)
  Other than that, I like your variable names/methods/overall style of writing, it's very clear to understand. Keep up the good work!
