### ISSUE TITLE
code review req

### ISSUE THREAD

**Issue by bilalyasar** [bounswe/bounswe2015group7#175]
@fthdgn please review my commit https://github.com/bounswe/bounswe2015group7/commit/c66ce19be3d40d9e9e6a919fe2d737e3aa50f1df

**Comment by empaksoy** [comment]
please create a pull request and assign to me

**Comment by fthdgn** [comment]
This commit is already on master. You should review it on this issue.

**Comment by safaorhan** [comment]
I will review it.

**Comment by bilalyasar** [comment]
@safaorhan please write comments here

**Comment by safaorhan** [comment]
I commented on the commit https://github.com/bounswe/bounswe2015group7/commit/c66ce19be3d40d9e9e6a919fe2d737e3aa50f1df also.

Here is a copy in case someone may omit:
- Please use camelCase in the both class fields and the function parameters.
- Please add unit tests.
- Wrong exception on the line: https://github.com/bounswe/bounswe2015group7/commit/c66ce19be3d40d9e9e6a919fe2d737e3aa50f1df#diff-53daf4ba68e3ce9100fbbfaca8d01cd8R171
- Setters are not necessary in `TagResponse.java`.
- Please add javadoc to this function since that it is a public function in the line: https://github.com/bounswe/bounswe2015group7/commit/c66ce19be3d40d9e9e6a919fe2d737e3aa50f1df#diff-53daf4ba68e3ce9100fbbfaca8d01cd8R164
