### ISSUE TITLE
Registration bag crash down

### ISSUE THREAD

**Issue by fthdgn** [bounswe/bounswe2015group7#71]
The registration page (http://52.28.216.93:8080/sculture/sculture) crashes. After restarting TOMCAT, it works again.

**Comment by bilalyasar** [comment]
let me look it.

**Comment by bilalyasar** [comment]
since we are connecting to database only `init` method in servlet. (since this method is just called only when tomcat starts).. After sometime, database connection timed out and all connections get failure. So i fixed  the issue via commit : https://github.com/bounswe/bounswe2015group7/commit/427cf5e61c99bde8296f68f3032efa4768da3a57

**Comment by bilalyasar** [comment]
if you encounter the problem again please reopen the issue.
